export const ENROLLMENT_NAME = 'Registration'
export const ENROLLMENT_TITLE = 'Create Account'
export const ENROLLMENT_HEADER_DESCRIPTION = 'Already have an account?'
export const ENROLLMENT_STATEMENT_1 = 'By clicking Register, I confirm that I have read and agree to the '
export const ENROLLMENT_STATEMENT_2 = ' and the '
export const ENROLLMENT_POLICY = 'Cisco Online Privacy Statement'
export const ENROLLMENT_TERMS_CONDITIONS = ' Cisco Web Site Terms and Conditions.'

export const LINK_ACCOUNT_TITLE = 'Create a Linked Account'
export const LINK_ACCOUNT_HEADER_DESCRIPTION = 'Learn more about'
export const LINKED_ACCOUNTS = "Linked Accounts"

export const ABOUT_LINKING_TITLE = 'More about account linking'
export const ABOUT_LINKING_HEADER_DESCRIPTION = 'Return to'
export const ABOUT_LINKING_QUESTION_1 = 'Why am I being asked to register for a new account?'
export const ABOUT_LINKING_QUESTION_2 = 'Does this mean I have to start from scratch? What happens to my previous account information?'
export const ABOUT_LINKING_QUESTION_3 = 'Can I opt out of linking?'
export const ABOUT_LINKING_ANSWER_1 = 'With this latest version of our cisco.com user account system, we use “email address” as the primary identifier to provide users with the appropriate level of access. Therefore, if you need to change your current email address for any reason (such as change of company), we may direct you to re-register with your new email address.'
export const ABOUT_LINKING_ANSWER_2 = 'We will help you create a new account by prefilling your latest account information, which you can modify during the registration process. Afterwards, go to your profile in order to request access based on your company association. Your previous account will remain available and associated with your new account, making transfer of previous Cisco assets (such as certifications) possible.'
export const ABOUT_LINKING_ANSWER_3_1 = 'Certifications will be transferred to your new account. If you are unable to view your certification through your new account. Please go to our '
export const ABOUT_LINKING_ANSWER_3_2 = ' page, choose “Other Issues” and request to transfer certifications. You will then be contacted by a customer service representative to update you about the transfer process. Please have your Certification Key (available in the security tab in your profile) to get the accurate updates on your transfer.'
export const ABOUT_LINKING_FEEDBACK_TO = 'We welcome you feedback to '
export const ABOUT_LINKING_LINKED_REGISTRATION = 'Linked account registration'
export const ABOUT_LINKING_REGISTRATION = 'register for an unlinked account here.'
export const ENROLLMENT_REDIRECT_LOGIN_TITLE = 'Thank you!'
export const ENROLLMENT_REDIRECT_LOGIN_TITLE_DESC = 'Registration process is now complete. You will be automatically redirected to OneIdentity Login Page...'
